// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using la_mia_pizzeria_static.Models;

#nullable disable

namespace la_mia_pizzeria_static.Migrations
{
    [DbContext(typeof(PizzasContext))]
    partial class PizzasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("la_mia_pizzeria_static.Models.PizzaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "PizzaFantastica",
                            Name = "Margherita",
                            Price = 12
                        },
                        new
                        {
                            Id = 2,
                            Description = "PizzaFantastica",
                            Name = "Diavola",
                            Price = 5
                        },
                        new
                        {
                            Id = 3,
                            Description = "PizzaFantastica",
                            Name = "Funghi",
                            Price = 6
                        },
                        new
                        {
                            Id = 4,
                            Description = "PizzaFantastica",
                            Name = "Tonno",
                            Price = 23
                        },
                        new
                        {
                            Id = 5,
                            Description = "PizzaFantastica",
                            Name = "Melanzane",
                            Price = 4
                        },
                        new
                        {
                            Id = 6,
                            Description = "PizzaFantastica",
                            Name = "Capricciosa",
                            Price = 32
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
